version: '3.8'

services:
  web:
    build: .
    command: gunicorn main.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - static_volume:/DockerBackend/static
      - media_volume:/DockerBackend/media
    env_file:
      - main/.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=cars_django_admin
      - POSTGRES_PASSWORD=cars_django_pass
      - POSTGRES_DB=cars_django_dev

volumes:
  postgres_volume:
  static_volume:
  media_volume:
