version: '3.7'

services:
  web:
    build: .
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    command: gunicorn main.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - main/.env.dev
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

  nginx:
    build: ./nginx
    volumes:
      -static_volume:/var/www/html/static
      -media_volume:/var/www/html/media
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
  media_volume:
