version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 45.84.225.230:8000
    volumes:
      - .:/carrs-app_team-project
    ports:
      - 8000:8000
    env_file:
      - main/.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
volumes:
  postgres_data:
