# Generated by Django 4.1.1 on 2022-09-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50, verbose_name='Марка автомобиля')),
                ('gear', models.CharField(max_length=50, verbose_name='Трансмиссия')),
                ('engine', models.CharField(max_length=3, verbose_name='Объем двигателя')),
                ('places', models.IntegerField(max_length=2, verbose_name='Количество мест')),
                ('image', models.CharField(max_length=100, verbose_name='Ссылка на изображение автомобиля')),
            ],
        ),
    ]
