# Generated by Django 4.1.1 on 2022-09-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='places',
            field=models.IntegerField(verbose_name='Количество мест'),
        ),
    ]
