# Generated by Django 4.1.1 on 2022-09-20 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_cars_places'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
    ]
