# Generated by Django 4.1.1 on 2022-09-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_cars_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='image',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ссылка на изображение автомобиля'),
        ),
    ]
