# Generated by Django 4.1.5 on 2023-01-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50, verbose_name='Марка автомобиля')),
                ('gear', models.CharField(max_length=50, verbose_name='Трансмиссия')),
                ('engine', models.CharField(max_length=3, verbose_name='Объем двигателя')),
                ('places', models.IntegerField(verbose_name='Количество мест')),
                ('image', models.CharField(blank=True, max_length=100, verbose_name='Ссылка на изображение автомобиля')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
